# Utiliser l'image Node.js LTS la plus récente
FROM rg.fr-par.scw.cloud/epitech-nantes-at/trinity-node22-pnpm-git-alpine:latest AS base

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de configuration
COPY package*.json ./

# Installer les dépendances
RUN pnpm install

# Copier le code source
COPY . .

# Exposer le port utilisé par Nuxt (habituellement 3000)
EXPOSE 3000

# Démarrer Nuxt en mode développement
CMD ["pnpm", "dev"]
